### ISSUE TITLE
Actividad 3 Sintesis

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-3-sintesis-Abraham890#2]

**Comment by Rosa218** [comment]
Calificacion :20

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
El trabajo es individual

**Comment by Abraham890** [comment]
[Abraham_Reyes_Ortiz_Sintexis_7US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Abraham890/files/9473103/Abraham_Reyes_Ortiz_Sintexis_7US.pdf)

**Comment by Abraham890** [comment]
Trabajo Corregido
